name: camabelcommunity

description: "Camabel Community App"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  logger: ^2.6.2
  flutter_launcher_icons: ^0.14.4
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  fpdart: ^1.2.0
  get_it: ^9.2.0
  dio: ^5.9.0
  google_fonts: ^8.0.1
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  test: ^1.26.3
  mocktail: ^1.0.4

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/covers/
    - assets/data_sample/
    - assets/img/splash/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo_camabel.png"
  min_sdk_android: 21

flutter_native_splash:

  color: "#FFFFFF"  ##====================================[REQUIRED]==========
  image: assets/img/splash/logo_splash_text.png  

  color_dark: "#FFFFFF"
  image_dark: assets/img/splash/logo_splash_text.png  
  fullscreen: true               
  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/img/splash/logo_splash_text.png  
    image_dark: assets/img/splash/logo_splash_text.png  

   
    icon_background_color: "#FFFFFF"